import Link from "next/link";
import { notFound } from "next/navigation";

type Layer={title:string;bn:string;intro:string;sections:{k:string;h:string;p:string}[];facts:string[];queue:string[]};

const data:Record<string,Layer>={
people:{title:"People",bn:"মানুষ",intro:"গাবুরার মানুষকে population-এর বাইরে গিয়ে দেখা—পরিবার, পেশা, স্থান, স্মৃতি এবং সময়ের সঙ্গে বদলে যাওয়া জীবনের record হিসেবে।",sections:[
{k:"01 / BASELINE",h:"জনসংখ্যা একটি starting point, পুরো গল্প নয়",p:"২০১১ সালের Census baseline-এ গাবুরার জনসংখ্যা 31,115 এবং household 6,753। ২০১৯ সালের একটি গবেষণা-উৎসে 43,262 মানুষ ও 8,321 household-এর figure উদ্ধৃত হয়েছে। বছর ও source আলাদা হওয়ায় এই সংখ্যাগুলোকে একই সময়ের data হিসেবে মেশানো যাবে না।"},
{k:"02 / PEOPLE",h:"মানুষের পরিচয় বহুস্তরীয়",p:"একজন মানুষের record-এ নামের পাশাপাশি village/locality, occupation, education, family context, migration, oral history এবং সংশ্লিষ্ট document রাখা হবে। ব্যক্তিগত তথ্য প্রকাশের ক্ষেত্রে privacy ও consent বাধ্যতামূলক হবে।"},
{k:"03 / MEMORY",h:"Oral history-ও evidence—কিন্তু তার label থাকবে",p:"প্রবীণদের স্মৃতি, family history এবং interview archive-এর গুরুত্বপূর্ণ অংশ। তবে স্মৃতিকে সরকারি record বা independently verified fact হিসেবে দেখানো হবে না; interviewee, date, place এবং corroboration status আলাদা থাকবে."}],facts:["2011 population: 31,115","2011 households: 6,753","2011 literacy: 35.9%","2011 age 0–19: 45.21%"],queue:["Current village-wise population","Household change","People directory with consent","Oral-history collection"]},
community:{title:"Community",bn:"সম্প্রদায় ও সমাজ",intro:"গাবুরার community life বোঝার জন্য neighbourhood, institution, social networks এবং collective response-এর records একসঙ্গে রাখা হবে।",sections:[
{k:"01 / SOCIAL FABRIC",h:"পাড়া ও প্রতিষ্ঠান",p:"Community records-এ village/locality, mosque/madrasa, school, market, social organisation, disaster committee এবং অন্যান্য collective institution-এর তথ্য থাকবে।"},
{k:"02 / COLLECTIVE ACTION",h:"দুর্যোগে community response",p:"গাবুরায় cyclone, tidal flooding ও waterlogging-এর সময় স্থানীয় মানুষ বাঁধ রক্ষা, আশ্রয় ও recovery-তে অংশ নেয়—এ ধরনের ঘটনার date, location ও source সহ আলাদা event record করা হবে।"},
{k:"03 / CIVIL SOCIETY",h:"সংগঠন ও স্থানীয় উদ্যোগ",p:"পুরোনো ইউনিয়ন profile-এ ASA, BRAC, Shushilan, Caritas এবং Nowabeki Gonomukhi Foundation-এর মতো organisation-এর কাজের উল্লেখ আছে। এগুলোর বর্তমান status আলাদাভাবে verify করতে হবে।"}],facts:["15 villages listed in official union profile","9 wards","Community institutions require current verification"],queue:["Institution directory","Community groups","Religious/social institutions","Disaster volunteer networks"]},
education:{title:"Education",bn:"শিক্ষা",intro:"গাবুরার শিক্ষার ইতিহাস শুধু স্কুলের সংখ্যা নয়—access, teacher, student, dropout, literacy এবং island geography-এর গল্প।",sections:[
{k:"01 / ACCESS",h:"শিক্ষা ও দূরত্ব",p:"২০১৫ সালের profile-এ 12 government primary schools, 2 secondary schools এবং 3 secondary madrasas-এর কথা বলা হয়েছে। এগুলো historical snapshot; current institution list আলাদা করে যাচাই করতে হবে।"},
{k:"02 / LITERACY",h:"শিক্ষার baseline",p:"2011 Census অনুযায়ী literacy 35.9%; male 38.8% এবং female 33.2%। এই gap historical baseline হিসেবে রাখা হবে, current rate হিসেবে নয়।"},
{k:"03 / HISTORY",h:"স্থানীয় শিক্ষার স্মৃতি",p:"স্থানীয় school history-তে neighbourhood pathshala/maktab থেকে formal schooling এবং Gabura Gopal Lakshmi Memorial Secondary School-এর প্রতিষ্ঠার narrative পাওয়া যায়। Archive-এ institutional claim ও oral/local narrative আলাদা label করা হবে."}],facts:["12 govt primary schools — 2015 profile","2 secondary schools — 2015 profile","3 secondary madrasas — 2015 profile","Literacy 35.9% — Census 2011"],queue:["Current school registry","Teacher/student records","Dropout history","School oral histories"]},
health:{title:"Health",bn:"স্বাস্থ্য",intro:"উপকূলীয় isolation, পানি, salinity, transport এবং medical access—গাবুরার health story-কে এই কয়েকটি layer-এর সঙ্গে পড়তে হবে।",sections:[
{k:"01 / SERVICES",h:"প্রাথমিক স্বাস্থ্যসেবার পুরোনো snapshot",p:"২০১৫ সালের profile-এ 1 Family Welfare Centre, 4 functional community clinics এবং 8 satellite clinics-এর উল্লেখ আছে। বর্তমান status, staffing ও service hours verify করা প্রয়োজন।"},
{k:"02 / WATER",h:"নিরাপদ পানির সঙ্গে স্বাস্থ্যের সম্পর্ক",p:"2015 profile-এ safe-water access-এর আলাদা statistics আছে এবং সাম্প্রতিক project sources-ও potable water access-কে বড় challenge হিসেবে বর্ণনা করে। পানি-উৎস, salinity ও seasonal availability আলাদা dataset হবে।"},
{k:"03 / ACCESS",h:"চিকিৎসা পাওয়া মানেই শুধু facility থাকা নয়",p:"Island geography ও transport disruption-এর কারণে emergency care-এর বাস্তব access distance, travel time, boat availability এবং referral route দিয়ে মাপা হবে।"}],facts:["1 Family Welfare Centre — 2015 profile","4 functional community clinics — 2015 profile","8 satellite clinics — 2015 profile","Current status: verify"],queue:["Facility GPS","Current staffing","Emergency referral routes","Water quality/salinity records"]},
livelihood:{title:"Livelihood",bn:"জীবিকা",intro:"গাবুরার অর্থনীতি পানি, জমি, নদী, সুন্দরবন এবং জলবায়ুর সঙ্গে সরাসরি যুক্ত।",sections:[
{k:"01 / FISHERIES",h:"চিংড়ি, মাছ ও কাঁকড়া",p:"Union profile-এ crab fattening-কে গুরুত্বপূর্ণ livelihood হিসেবে দেখানো হয়েছে। গবেষণাতেও shrimp farming, fishing, marketing, boat-making ও net-mending-এর মতো fisheries-linked কাজ নথিবদ্ধ হয়েছে।"},
{k:"02 / AGRICULTURE",h:"কৃষি এখনও গুরুত্বপূর্ণ—কিন্তু salinity বদলে দিয়েছে বাস্তবতা",p:"Paddy, vegetable এবং other crops-এর উল্লেখ official profile-এ আছে। গবেষণা বলছে salinity ও cyclones-এর ফলে agriculture থেকে water-based livelihoods-এর দিকে পরিবর্তন হয়েছে।"},
{k:"03 / SEASONAL WORK",h:"কাজের season বদলায়",p:"Union profile-এ winter season-এ কাজ ও income-এর সংকট এবং বাইরে গিয়ে কাজ খোঁজার কথা বলা হয়েছে। এই seasonal movement-কে migration section-এর সঙ্গে link করা হবে।"}],facts:["Crab fattening: major livelihood in union profile","Shrimp/fisheries: major economic activity","Paddy: main crop in profile","Winter work shortage documented"],queue:["Occupation by village","Income seasonality","Crab/shrimp value chain","Agriculture-to-aquaculture change"]},
"women-and-children":{title:"Women & Children",bn:"নারী ও শিশু",intro:"নারী ও শিশুদের records হবে rights, education, health, labour, safety এবং climate vulnerability-এর intersection ধরে।",sections:[
{k:"01 / EDUCATION",h:"শিশুর শিক্ষা বনাম livelihood pressure",p:"Union profile-এ fishing boats-এ শিশুদের যুক্ত হওয়ার ফলে education rights-এর concern উল্লেখ আছে। এই claim-কে dated source হিসেবে রাখা হবে; current child-labour status আলাদা survey ছাড়া অনুমান করা হবে না।"},
{k:"02 / WOMEN",h:"নারীর জীবন আলাদা data layer চায়",p:"Literacy baseline-এ female literacy 33.2% ছিল। নারী-led household, unpaid care, livelihood participation, health এবং decision-making-এর current records তৈরি করা হবে।"},
{k:"03 / SAFETY",h:"দুর্যোগে vulnerability",p:"Cyclone, waterlogging, safe water এবং transport disruption নারী ও শিশুদের জন্য আলাদা risk তৈরি করতে পারে। archive-এ evidence ছাড়া generalisation করা হবে না; interview ও service records দিয়ে যাচাই করা হবে।"}],facts:["Female literacy: 33.2% — 2011","Child labour concern documented in 2015 profile","Current gender-disaggregated data: research needed"],queue:["Women-led households","Girls' education","Child labour evidence","Maternal/child health"]},
youth:{title:"Youth",bn:"তরুণ প্রজন্ম",intro:"গাবুরার তরুণরা শিক্ষা, কাজ, migration, sport এবং digital connectivity-এর মাঝখানে দাঁড়িয়ে থাকা একটি changing generation।",sections:[
{k:"01 / OPPORTUNITY",h:"শিক্ষা থেকে কাজ",p:"Low literacy baseline, seasonal employment এবং livelihood change তরুণদের পথকে প্রভাবিত করতে পারে। Archive-এ এই বিষয়গুলো verified survey ও interview দিয়ে document করা হবে।"},
{k:"02 / MIGRATION",h:"বাইরে যাওয়া কেন?",p:"Climate and livelihood research in coastal Satkhira reports employment-driven migration, including movement toward Satkhira, Khulna and beyond. Gabura-specific current patterns এখনও আলাদা করে map করা প্রয়োজন।"},
{k:"03 / SPORT & CULTURE",h:"মাঠও social infrastructure",p:"স্থানীয় football ও community events তরুণদের collective identity-এর অংশ হতে পারে। Tournament, মাঠ, team এবং participant records evidence সহ সংগ্রহ করা হবে।"}],facts:["Age 0–19: 45.21% in 2011 baseline","Employment-linked migration documented in regional research","Current youth population: verify"],queue:["Youth survey","Training/employment","Digital access","Sports participation"]},
migration:{title:"Migration",bn:"অভিবাসন",intro:"Migration-কে শুধু ‘মানুষ চলে যায়’ হিসেবে নয়—কাজ, climate pressure, family strategy ও seasonal income-এর সঙ্গে সম্পর্কিত process হিসেবে document করা হবে।",sections:[
{k:"01 / WORK",h:"কাজের জন্য seasonal movement",p:"Union profile-এ winter season-এ কাজের অভাবে দূরে গিয়ে income খোঁজার কথা আছে। এটি migration research-এর গুরুত্বপূর্ণ local baseline।"},
{k:"02 / CLIMATE",h:"জলবায়ু ও migration",p:"BRAC University-এর 2012 field research-এ Gabura-সহ Satkhira coastal communities-এ salinity, livelihood pressure এবং employment-driven migration-এর সম্পর্ক documented হয়েছিল।"},
{k:"03 / DESTINATION",h:"কোথায় যায়?",p:"2012 research-এ Satkhira, Khulna এবং দেশের বাইরেও movement-এর কথা পাওয়া যায়। বর্তমান destination, duration, remittance এবং return migration আলাদা survey ছাড়া অনুমান করা হবে না।"}],facts:["Seasonal work shortage documented","2012 study links livelihood pressure with migration","Current migration map: research needed"],queue:["Origin/destination map","Seasonal migration","Remittance","Climate displacement records"]},
culture:{title:"Culture",bn:"সংস্কৃতি",intro:"গাবুরার culture হলো মানুষের দৈনন্দিন জীবন, ভাষা, আচার, ধর্মীয় ও সামাজিক অনুষ্ঠান, খাবার, স্মৃতি এবং coastal environment-এর সঙ্গে তৈরি হওয়া identity।",sections:[
{k:"01 / MEMORY",h:"Oral tradition as cultural archive",p:"স্থানীয় নাম, settlement stories, school histories এবং elder memories cultural record-এর অংশ। এগুলো narrator, date ও context-সহ সংরক্ষণ করা হবে।"},
{k:"02 / DAILY LIFE",h:"জীবনযাপনও heritage",p:"মাছ ধরা, নৌযাত্রা, কৃষি, বাজার, বনজ সম্পদ সংগ্রহ, স্থানীয় খাবার ও seasonal practices-এর ছবি/ভিডিও/ইন্টারভিউ future archive-এর primary material হতে পারে।"},
{k:"03 / CHANGE",h:"সংস্কৃতি বদলায়",p:"Cyclone, migration, livelihood transition ও digital media community practices বদলে দিতে পারে। Archive পুরোনো ও নতুন practice পাশাপাশি রাখবে।"}],facts:["Local oral histories are an evidence stream","Gabura has documented fishing/forest-linked livelihood traditions","Systematic culture inventory: research needed"],queue:["Oral history","Local vocabulary","Food traditions","Festivals/music/craft archive"]},
sports:{title:"Sports",bn:"খেলাধুলা",intro:"খেলাধুলা গাবুরার তরুণদের সময় কাটানোর বিষয়ই নয়—এটি community gathering, local identity এবং public space-এর archive।",sections:[
{k:"01 / FOOTBALL",h:"স্থানীয় football culture",p:"Gabura-তে Martello Cup একটি স্থানীয় football tournament হিসেবে community sports archive-এর গুরুত্বপূর্ণ অংশ। Season, team, venue, fixture, result, player এবং media evidence আলাদা করে রাখা হবে।"},
{k:"02 / SPACES",h:"মাঠ কোথায়?",p:"Sports archive-এ মাঠের location, condition, access, flood/waterlogging এবং event history রাখা হবে—কারণ মাঠও community infrastructure।"},
{k:"03 / PEOPLE",h:"খেলোয়াড় থেকে organiser",p:"Player, referee, coach, organiser, volunteer ও supporter—সব role আলাদা person/event relationship হিসেবে সংরক্ষণ করা হবে।"}],facts:["Martello Cup: local football tournament","Sports records should be season/date based","Current player directory: research needed"],queue:["Ground map","Tournament archive","Player profiles","Historical sports teams"]}
};

export default async function PeopleLayerPage({params}:{params:Promise<{slug:string}>}) {
 const {slug}=await params;
 const item=data[slug];
 if(!item) notFound();
 return <main>
  <header className="nav"><div className="wrap history-nav"><Link className="brand" href="/people">PEOPLE / GABURA ARCHIVE</Link><Link className="navlink" href="/people">← PEOPLE</Link></div></header>
  <section className="layer-hero"><div className="wrap"><div className="eyebrow">SECTION 02 / PEOPLE / {slug.toUpperCase()}</div><h1>{item.title}<br/><em>{item.bn}</em></h1><p>{item.intro}</p><div className="layer-meta"><span>Evidence-led</span><span>Time-aware</span><span>Research archive</span></div></div></section>
  <section className="layer-content"><div className="wrap">
   <div className="layer-grid">{item.sections.map(s=><article key={s.k}><div className="eyebrow">{s.k}</div><h2>{s.h}</h2><p>{s.p}</p></article>)}</div>
  </div></section>
  <section className="layer-facts"><div className="wrap facts-grid"><div><div className="eyebrow">Known records</div><h2>What the archive can say now</h2></div><div className="fact-list">{item.facts.map((x,i)=><div key={i}><span>{String(i+1).padStart(2,"0")}</span>{x}</div>)}</div></div></section>
  <section className="layer-queue"><div className="wrap"><div className="eyebrow">Research queue</div><h2>Next evidence to collect</h2><div className="queue-grid">{item.queue.map((x,i)=><div key={x}><b>{String(i+1).padStart(2,"0")}</b>{x}</div>)}</div></div></section>
  <footer className="layer-footer"><div className="wrap"><Link href="/people">Return to PEOPLE</Link><Link href="/">GABURA ARCHIVE</Link></div></footer>
 </main>;
}
